### ISSUE TITLE
AuthAPIClient.refreshAccessToken throws AuthAPIClient instead of ApiError

### ISSUE THREAD

**Issue by joshdifabio** [TrueLayer/truelayer-client-javascript#20]
https://github.com/TrueLayer/truelayer-client-javascript/blob/07211b8055a17d8a3cc6d37fa95a847d41dce780/src/v1/AuthAPIClient.ts#L168-L170

Presumably this should be throwing an `ApiError`, not an `AuthAPIClient`.

Note that fixing this would unfortunately constitute an API break.

**Comment by mayankamencherla** [comment]
We have fixed this issue. Thank you for reporting it to us!

**Comment by gkapkowski** [comment]
When will you release fixed version?
