### ISSUE TITLE
Support all options for getAuthUrl

### ISSUE THREAD

**Issue by smontiu** [TrueLayer/truelayer-client-javascript#28]
Hi!

There will be an update to add full options to getAuthUrl method, including :

- provider_id
- enable_open_banking_providers
- enable_credentials_sharing_providers
- enable_credentials_sharing_providers_de
- enable_oauth_providers
- disable_providers

Thanks

**Comment by smontiu** [comment]
Pending PR: [](https://github.com/TrueLayer/truelayer-client-javascript/pull/29)

**Comment by riccardoio** [comment]
Hi @smontiu 

Thank you for your PR! We have merged it.
