### ISSUE TITLE
Latest release on npm does not include src directory

### ISSUE THREAD

**Issue by hueyy** [TrueLayer/truelayer-client-javascript#34]
[v1.3.0, published about 11 hours ago](https://www.npmjs.com/package/truelayer-client/v/1.3.0) is missing the entire `src` directory (and the `test` directory as well)

![image](https://user-images.githubusercontent.com/6523121/63205763-bd6e3d00-c0db-11e9-9feb-0e576c66ff2c.png)

Since `index.js` tries to import modules from the missing src directory, it will throw an error

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './src/v1/AuthAPIClient'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by JarvisPrestidge** [comment]
@hueyy thanks for reporting, this is now fixed. A new version v1.3.1 with some better npm publishing practices has been released also. Thanks again!
